package com.springcloud.ufire.core.mapper;

import com.springcloud.ufire.core.model.MessageUser;
import com.springcloud.ufire.core.model.MessageUserExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MessageUserMapper extends UpsertMapper<Integer, MessageUser, MessageUserExample>, ReadMapper<Integer, MessageUser, MessageUserExample>, WriteMapper<Integer, MessageUser, MessageUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated
     */
    default MessageUser selectByPrimaryKeyWithColumns(Integer primaryKey, boolean include, MessageUserExample.C... cs) {
        MessageUserExample example = new MessageUserExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andIdEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}