package com.springcloud.ufire.core.mapper;

import com.springcloud.ufire.core.model.ResetUser;
import com.springcloud.ufire.core.model.ResetUserExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ResetUserMapper extends UpsertMapper<Integer, ResetUser, ResetUserExample>, ReadMapper<Integer, ResetUser, ResetUserExample>, WriteMapper<Integer, ResetUser, ResetUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    default ResetUser selectByPrimaryKeyWithColumns(Integer primaryKey, boolean include, ResetUserExample.C... cs) {
        ResetUserExample example = new ResetUserExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andIdEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}