package com.springcloud.ufire.core.mapper;

import com.springcloud.ufire.core.model.User;
import com.springcloud.ufire.core.model.UserExample;
import mboog.support.mapper.ReadMapper;
import mboog.support.mapper.UpsertMapper;
import mboog.support.mapper.WriteMapper;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserMapper extends UpsertMapper<Integer, User, UserExample>, ReadMapper<Integer, User, UserExample>, WriteMapper<Integer, User, UserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    default User selectByPrimaryKeyWithColumns(Integer primaryKey, boolean include, UserExample.C... cs) {
        UserExample example = new UserExample();
        if (include) {
                example.includeColumns(cs);
        } else {
                example.excludeColumns(cs);
        }
        example.or(cri -> cri
               .andIdEqualTo(primaryKey)
        );
        return selectByExampleSingleResult(example);
    }
}