package com.springcloud.ufire.core.service.impl;

import com.springcloud.ufire.core.mapper.MessageLogMapper;
import com.springcloud.ufire.core.model.MessageLog;
import com.springcloud.ufire.core.model.MessageLogExample;
import com.springcloud.ufire.core.service.MessageLogService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class MessageLogServiceImpl extends ServiceSupport<String, MessageLog, MessageLogExample, MessageLogMapper> implements MessageLogService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table broker_message_log
     *
     * @mbg.generated
     */
    @Resource
    private MessageLogMapper messageLogMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table broker_message_log
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = messageLogMapper;
    }
}