package com.springcloud.ufire.core.service.impl;

import com.springcloud.ufire.core.mapper.MessageUserMapper;
import com.springcloud.ufire.core.model.MessageUser;
import com.springcloud.ufire.core.model.MessageUserExample;
import com.springcloud.ufire.core.service.MessageUserService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class MessageUserServiceImpl extends ServiceSupport<Integer, MessageUser, MessageUserExample, MessageUserMapper> implements MessageUserService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table message_user
     *
     * @mbg.generated
     */
    @Resource
    private MessageUserMapper messageUserMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message_user
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = messageUserMapper;
    }
}