package com.springcloud.ufire.core.service.impl;

import com.springcloud.ufire.core.mapper.ResetUserMapper;
import com.springcloud.ufire.core.model.ResetUser;
import com.springcloud.ufire.core.model.ResetUserExample;
import com.springcloud.ufire.core.service.ResetUserService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class ResetUserServiceImpl extends ServiceSupport<Integer, ResetUser, ResetUserExample, ResetUserMapper> implements ResetUserService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    @Resource
    private ResetUserMapper resetUserMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = resetUserMapper;
    }
}