package com.springcloud.ufire.core.service.impl;

import com.springcloud.ufire.core.mapper.UserMapper;
import com.springcloud.ufire.core.model.User;
import com.springcloud.ufire.core.model.UserExample;
import com.springcloud.ufire.core.service.UserService;
import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import mboog.support.service.ServiceSupport;
import org.springframework.stereotype.Service;

@Service
public class UserServiceImpl extends ServiceSupport<Integer, User, UserExample, UserMapper> implements UserService {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user
     *
     * @mbg.generated
     */
    @Resource
    private UserMapper userMapper;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated
     */
    @PostConstruct
    private void initService() {
        super.mapper = userMapper;
    }
}