package com.springcloud.ufire.core.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reset_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ResetUser implements Serializable {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   消息id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.message_id
     *
     * @mbg.generated
     */
    private String messageId;

    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   目标地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.reset_link
     *
     * @mbg.generated
     */
    private String resetLink;

    /**
     * Database Column Remarks:
     *   原地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.original_link
     *
     * @mbg.generated
     */
    private String originalLink;

    /**
     * Database Column Remarks:
     *   routing_key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reset_user.routing_key
     *
     * @mbg.generated
     */
    private String routingKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.id
     *
     * @return the value of reset_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.id
     *
     * @param id the value for reset_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.name
     *
     * @return the value of reset_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.name
     *
     * @param name the value for reset_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.message_id
     *
     * @return the value of reset_user.message_id
     *
     * @mbg.generated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.message_id
     *
     * @param messageId the value for reset_user.message_id
     *
     * @mbg.generated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.user_id
     *
     * @return the value of reset_user.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.user_id
     *
     * @param userId the value for reset_user.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.reset_link
     *
     * @return the value of reset_user.reset_link
     *
     * @mbg.generated
     */
    public String getResetLink() {
        return resetLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.reset_link
     *
     * @param resetLink the value for reset_user.reset_link
     *
     * @mbg.generated
     */
    public void setResetLink(String resetLink) {
        this.resetLink = resetLink == null ? null : resetLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.original_link
     *
     * @return the value of reset_user.original_link
     *
     * @mbg.generated
     */
    public String getOriginalLink() {
        return originalLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.original_link
     *
     * @param originalLink the value for reset_user.original_link
     *
     * @mbg.generated
     */
    public void setOriginalLink(String originalLink) {
        this.originalLink = originalLink == null ? null : originalLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reset_user.routing_key
     *
     * @return the value of reset_user.routing_key
     *
     * @mbg.generated
     */
    public String getRoutingKey() {
        return routingKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reset_user.routing_key
     *
     * @param routingKey the value for reset_user.routing_key
     *
     * @mbg.generated
     */
    public void setRoutingKey(String routingKey) {
        this.routingKey = routingKey == null ? null : routingKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", messageId=").append(messageId);
        sb.append(", userId=").append(userId);
        sb.append(", resetLink=").append(resetLink);
        sb.append(", originalLink=").append(originalLink);
        sb.append(", routingKey=").append(routingKey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}