package com.springcloud.ufire.core.model;

import com.springcloud.ufire.core.model.ResetUserExample.C;
import com.springcloud.ufire.core.model.ResetUserExample.Criteria;
import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import mboog.support.example.AbstractExample;
import mboog.support.example.AbstractGeneratedCriteria;
import mboog.support.example.CInterface;
import mboog.support.example.CItem;
import mboog.support.example.ColumnListAble;
import mboog.support.example.PaginationAble;

@SuppressWarnings("unused")
public class ResetUserExample extends AbstractExample<ResetUserExample, Criteria, C> implements Serializable, ColumnListAble<ResetUserExample, C, C>, PaginationAble<ResetUserExample> {
    
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    public ResetUserExample() {
        supplier = Criteria::new;
        initColumnList(C.class);
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria extends AbstractGeneratedCriteria<Criteria> {

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String pattern, String value) {
            addCriterionPattern("`name` like", pattern, value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String pattern, String value) {
            addCriterionPattern("`name` not like", pattern, value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("message_id is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("message_id is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("message_id =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("message_id <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("message_id >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("message_id >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("message_id <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("message_id <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String pattern, String value) {
            addCriterionPattern("message_id like", pattern, value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String pattern, String value) {
            addCriterionPattern("message_id not like", pattern, value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("message_id in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("message_id not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("message_id between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("message_id not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String pattern, String value) {
            addCriterionPattern("user_id like", pattern, value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String pattern, String value) {
            addCriterionPattern("user_id not like", pattern, value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andResetLinkIsNull() {
            addCriterion("reset_link is null");
            return (Criteria) this;
        }

        public Criteria andResetLinkIsNotNull() {
            addCriterion("reset_link is not null");
            return (Criteria) this;
        }

        public Criteria andResetLinkEqualTo(String value) {
            addCriterion("reset_link =", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkNotEqualTo(String value) {
            addCriterion("reset_link <>", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkGreaterThan(String value) {
            addCriterion("reset_link >", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkGreaterThanOrEqualTo(String value) {
            addCriterion("reset_link >=", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkLessThan(String value) {
            addCriterion("reset_link <", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkLessThanOrEqualTo(String value) {
            addCriterion("reset_link <=", value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkLike(String pattern, String value) {
            addCriterionPattern("reset_link like", pattern, value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkNotLike(String pattern, String value) {
            addCriterionPattern("reset_link not like", pattern, value, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkIn(List<String> values) {
            addCriterion("reset_link in", values, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkNotIn(List<String> values) {
            addCriterion("reset_link not in", values, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkBetween(String value1, String value2) {
            addCriterion("reset_link between", value1, value2, "resetLink");
            return (Criteria) this;
        }

        public Criteria andResetLinkNotBetween(String value1, String value2) {
            addCriterion("reset_link not between", value1, value2, "resetLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkIsNull() {
            addCriterion("original_link is null");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkIsNotNull() {
            addCriterion("original_link is not null");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkEqualTo(String value) {
            addCriterion("original_link =", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkNotEqualTo(String value) {
            addCriterion("original_link <>", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkGreaterThan(String value) {
            addCriterion("original_link >", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkGreaterThanOrEqualTo(String value) {
            addCriterion("original_link >=", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkLessThan(String value) {
            addCriterion("original_link <", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkLessThanOrEqualTo(String value) {
            addCriterion("original_link <=", value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkLike(String pattern, String value) {
            addCriterionPattern("original_link like", pattern, value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkNotLike(String pattern, String value) {
            addCriterionPattern("original_link not like", pattern, value, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkIn(List<String> values) {
            addCriterion("original_link in", values, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkNotIn(List<String> values) {
            addCriterion("original_link not in", values, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkBetween(String value1, String value2) {
            addCriterion("original_link between", value1, value2, "originalLink");
            return (Criteria) this;
        }

        public Criteria andOriginalLinkNotBetween(String value1, String value2) {
            addCriterion("original_link not between", value1, value2, "originalLink");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyIsNull() {
            addCriterion("routing_key is null");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyIsNotNull() {
            addCriterion("routing_key is not null");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyEqualTo(String value) {
            addCriterion("routing_key =", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyNotEqualTo(String value) {
            addCriterion("routing_key <>", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyGreaterThan(String value) {
            addCriterion("routing_key >", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyGreaterThanOrEqualTo(String value) {
            addCriterion("routing_key >=", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyLessThan(String value) {
            addCriterion("routing_key <", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyLessThanOrEqualTo(String value) {
            addCriterion("routing_key <=", value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyLike(String pattern, String value) {
            addCriterionPattern("routing_key like", pattern, value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyNotLike(String pattern, String value) {
            addCriterionPattern("routing_key not like", pattern, value, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyIn(List<String> values) {
            addCriterion("routing_key in", values, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyNotIn(List<String> values) {
            addCriterion("routing_key not in", values, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyBetween(String value1, String value2) {
            addCriterion("routing_key between", value1, value2, "routingKey");
            return (Criteria) this;
        }

        public Criteria andRoutingKeyNotBetween(String value1, String value2) {
            addCriterion("routing_key not between", value1, value2, "routingKey");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reset_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria implements Serializable {
        
        private static final long serialVersionUID = 1L;

        protected Criteria() {
            super();
        }
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table reset_user
     *
     * @mbg.generated
     */
    public enum C implements CInterface {
        //--------------------------------------------------
		//[TABLE]
		//--------------------------------------------------
		/** id */					ID(1, Types.INTEGER, false, "id"),
		/** 名称 */					NAME(2, Types.VARCHAR, true, "name"),
		/** 消息id */				MESSAGE_ID(2, Types.VARCHAR, false, "message_id"),
		/** 用户id */				USER_ID(2, Types.VARCHAR, false, "user_id"),
		/** 目标地址 */				RESET_LINK(2, Types.VARCHAR, false, "reset_link"),
		/** 原地址 */				ORIGINAL_LINK(2, Types.VARCHAR, false, "original_link"),
		/** routing_key */			ROUTING_KEY(2, Types.VARCHAR, false, "routing_key");

        C(int types, int jdbcType, boolean delimited, String columnName) {
            init(new CItem(types, jdbcType, delimited, columnName, null , "`", "`"));
        }
    }
}